[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "new_ml_project"
version = "0.1.0"
dependencies = [
    "pandas",
    "numpy",
    "seaborn"
]

[tool.setuptools.packages.find]
include = ["src*"]
